language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_install:
- chmod +x .travis/setup.sh
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- .travis/setup.sh
script: xvfb-run wct
